basePath: /
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Hardware:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Doctra Middleware API
  version: "1.0"
paths:
  /hardwares:
    get:
      consumes:
      - application/json
      description: Get all hardwares
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get all hardwares
      tags:
      - Hardwares
    post:
      consumes:
      - application/json
      description: Create a new hardware
      parameters:
      - description: Hardware object
        in: body
        name: hardware
        required: true
        schema:
          $ref: '#/definitions/models.Hardware'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create a new hardware
      tags:
      - Hardwares
  /hardwares/{id}:
    delete:
      consumes:
      - application/json
      description: Delete hardware by ID
      parameters:
      - description: Hardware ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete hardware by ID
      tags:
      - Hardwares
    get:
      consumes:
      - application/json
      description: Get hardware by ID
      parameters:
      - description: Hardware ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get hardware by ID
      tags:
      - Hardwares
    put:
      consumes:
      - application/json
      description: Update hardware by ID
      parameters:
      - description: Hardware ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated hardware object
        in: body
        name: hardware
        required: true
        schema:
          $ref: '#/definitions/models.Hardware'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update hardware by ID
      tags:
      - Hardwares
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
